name: rna_binding
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8.3
  - numpy=1.21.2
  - scipy=1.7.1
  - pandas=1.3.3
  - matplotlib=3.4.3
  - scikit-learn=0.24.2
  - pytorch=1.10.0
  - rdkit=2021.09.4
  - pip=21.2.2
  - pip:
    - moleculekit==0.9.2